token: "$LICHESS_TOKEN"
url: "https://lichess.org/"

engine:
  dir: "./src/"
  name: "Ethereal"
  protocol: "uci"
  uci_options:
    Threads: 2            # GitHub Actions (2 Core) için tam verim
    Hash: 128             # 2800+ seviyesi için kritik. 256'dan 512'ye çıkardım (Daha derin analiz hafızası)
    MoveOverhead: 2000   # 2 saniye pay. Bot derin düşünürken internet lagı yüzünden süreyle kaybetmesin.
    #Contempt: 20          # ÖNEMLİ: Botun beraberliği hemen kabul etmemesini, galibiyet için baskı yapmasını sağlar.
    # Syzygy Ayarları (Dosyaları eklediğinde burası hazır olacak)
    SyzygyPath: "./syzygy"
    SyzygyProbeDepth: 1
    SyzygyProbeLimit: 6

# --- SAVAŞ MODU AYARLARI ---

challenge_policy:
  accept_bot: true
  accept_human: true
  rated: true
  modes:
    - rated               # Puan kasmak için sadece rated maçlar
  time_controls:
    - bullet
    - blitz
  min_time: 60
  max_time: 300           # Blitz ve Bullet uzmanlığını sürdürsün

matchmaking:
  allow_feed: true
  challenge_interval: 45        # Güvenli istek aralığı
  challenge_timeout: 30
  max_games: 1
  
  # --- ELO FİLTRESİ (PROFESYONEL AYAR) ---
  opponent_min_rating: 2000     # 2600 puandasın, 2450 altı botları yenmek sana puan vermez ama risk yaratır.
  opponent_max_rating: 3200     # 3100'ü 3200 yaptım, en üst seviyedeki devleri de listeye ekleyelim.
  opponent_rating_difference: 500 # Kendi ligindeki ve üstündeki botlarla eşleşsin.

  time_controls:
    - "1+0"
    - "2+1"
    - "3+0"
    - "3+2"
    - "5+0"
  challenge_bots: true
  challenge_humans: false
  selection: "random"           # Manipülasyon olarak algılanmaması için en güvenli yöntem.
